name: PR CI

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    strategy:
      matrix:
        app: [ shared, event, service ]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show git info
        run: |
          echo "Branch: $(git branch --show-current)"
          echo "SHA: $(git rev-parse --short HEAD)"

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
          cache-dependency-path: ${{ matrix.app }}/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --progress=false --fund=false --fetch-retries=5

      - name: Building
        run: npm run build

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test -- --ci
